version: '3.7'
services:
  front:
    build:
      context: .
      target: build-stage
      dockerfile: ./aksharamukha-front/Dockerfile
    image: dev-aksharamukha-front
    ports:
      - "12345:80"
    volumes:
      - './aksharamukha-front:/app'
      - /app/node_modules/
    command: /bin/sh -c "quasar dev"
  back:
    build:
      context: .
      dockerfile: ./aksharamukha-back/Dockerfile
    image: dev-aksharamukha-back
    volumes:
        - ./aksharamukha-back:/usr/backend/
        - ./aksharamukha-python-package/aksharamukha:/usr/backend/aksharamukha/
    ports:
      - "8085:8085"
  fonts:
    build:
      context: .
      dockerfile: ./aksharamukha-fonts/Dockerfile
    image: dev-aksharamukha-fonts
    volumes:
        - ./aksharamukha-fonts:/usr/local/apache2/htdocs/
    ports:
      - "9899:80"